name: Build .deb file

on:
  push:
    tags:
      - "v*" # Triggers on pushes to tags starting with "v"

permissions:
  contents: write

env:
  DEB_PACKAGE_NAME: ${{ github.event.repository.name }}
  TAG_NAME: ${{ github.ref_name }}
  VERSION: ${TAG_NAME#v}

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        id: get_repo_name
        run: |
          echo "Repository name: ${{ github.event.repository.name }}"

      - name: Get tag name and remove 'v'
        id: get_version
        run: |
          # TAG_NAME="${{ github.ref_name }}"
          # VERSION="${TAG_NAME#v}" # Removes a leading 'v' if present
          echo "Original Tag Name: $TAG_NAME"
          echo "Version (without 'v'): $VERSION"
          # echo "VERSION=$VERSION" >> $GITHUB_ENV # Make VERSION available to subsequent steps

      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v4
        with:
          path: "REPO"
     
      - name: Copy files to keep extraneous files out of the package
        id: copy_files
        run: |
          mkdir PKG_SOURCE
          cp -Rf REPO/usr REPO/DEBIAN PKG_SOURCE

      - name: Build .deb package
        id: build_deb_package
        run: |
          dpkg-deb --build PKG_SOURCE ${{ github.event.repository.name }}_${{ env.VERSION }}_all.deb
        
      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}_${{ env.VERSION }}_all.deb
